# --- !Ups

create table if not exists "user" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "firstName" varchar not null,
  "middleName" varchar,
  "lastName" varchar not null,
  "userName" varchar not null,
  "password" varchar not null,
  "confirmPassword" varchar not null,
  "mobileNumber" varchar not null,
  "gender" varchar not null,
  "age" int not null
);

# --- !Downs
DROP TABLE "user";
